PROXI_USER = 'XXXXXXXXX'
PROXI_PWD = 'XXXXXXXXX'
EMAIL = 'XXXXXXXXXXXXXXXXXX'
SUBJECT = 'Pronostico del Clima'
API_KEY_WAPI = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
PROXIES = {
    'http': 'XXXXXXXXX',
    'https': 'XXXXXXXXX'
}